-- ============================================
-- PAIC - Full Database Schema
-- Generated from live Supabase project
-- ============================================

-- Custom enum types
CREATE TYPE public.user_role AS ENUM ('trial', 'subscriber', 'internal', 'admin');

-- ============================================
-- TABLES
-- ============================================

-- Conjuntos (residential complexes)
CREATE TABLE public.conjuntos (
    id text NOT NULL,
    name text NOT NULL,
    nit text,
    address text,
    admin_name text,
    admin_email text,
    admin_phone text,
    subscription_plan text DEFAULT 'Free'::text NOT NULL,
    plan_price numeric,
    registration_date timestamp with time zone DEFAULT now()
);

-- User profiles (extends auth.users)
CREATE TABLE public.user_profiles (
    id uuid NOT NULL,
    email text,
    full_name text,
    avatar_url text,
    role public.user_role DEFAULT 'trial'::public.user_role,
    trial_expires_at timestamp with time zone,
    conjunto_id text
);

-- Residents database
CREATE TABLE public.residents (
    apartment text NOT NULL,
    name text NOT NULL,
    email text,
    phone text,
    conjunto_id text NOT NULL
);

-- Account status per apartment
CREATE TABLE public.account_status (
    apartment text NOT NULL,
    last_payment_date date,
    admin_fee_value numeric DEFAULT 0,
    pending_installments integer DEFAULT 0,
    other_charges numeric DEFAULT 0,
    outstanding_balance numeric DEFAULT 0,
    conjunto_id text NOT NULL
);

-- Service providers
CREATE TABLE public.providers (
    id integer NOT NULL,
    company text NOT NULL,
    specialty text,
    email text,
    phone text,
    conjunto_id text NOT NULL
);

-- Internal staff
CREATE TABLE public.internal_staff (
    name text NOT NULL,
    position text,
    email text,
    phone text,
    conjunto_id text NOT NULL
);

-- Platform users (non-admin)
CREATE TABLE public.users (
    id integer NOT NULL,
    name text NOT NULL,
    email text NOT NULL,
    phone_number text,
    role text NOT NULL,
    password text,
    conjunto_id text NOT NULL
);

-- Custom user roles with permissions
CREATE TABLE public.user_roles (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    name text NOT NULL,
    permissions text[],
    conjunto_id text NOT NULL
);

-- Common areas for booking
CREATE TABLE public.common_areas (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    name text NOT NULL,
    color jsonb,
    conjunto_id text NOT NULL
);

-- Bookings / reservations (legacy)
CREATE TABLE public.bookings (
    id integer NOT NULL,
    day integer NOT NULL,
    time text NOT NULL,
    event text NOT NULL,
    user text NOT NULL,
    conjunto_id text NOT NULL
);

-- Reservations (new system)
CREATE TABLE public.reservations (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    conjunto_id character varying NOT NULL,
    apartment character varying NOT NULL,
    resident_name character varying NOT NULL,
    common_area_id uuid NOT NULL,
    date date NOT NULL,
    start_time time without time zone NOT NULL,
    end_time time without time zone NOT NULL,
    email character varying,
    phone character varying,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

-- Due dates / payment obligations
CREATE TABLE public.due_dates (
    id integer NOT NULL,
    item text NOT NULL,
    category text NOT NULL,
    due_date date NOT NULL,
    status text NOT NULL,
    conjunto_id text NOT NULL
);

-- Tasks
CREATE TABLE public.tasks (
    id integer NOT NULL,
    text text NOT NULL,
    due_date date,
    completed boolean DEFAULT false,
    conjunto_id text NOT NULL
);

-- Expenses
CREATE TABLE public.expenses (
    id integer NOT NULL,
    description text NOT NULL,
    amount numeric NOT NULL,
    category text NOT NULL,
    date date NOT NULL,
    provider_id integer,
    conjunto_id text NOT NULL
);

-- Incomes
CREATE TABLE public.incomes (
    id integer NOT NULL,
    description text NOT NULL,
    amount numeric NOT NULL,
    category text NOT NULL,
    date date NOT NULL,
    conjunto_id text NOT NULL
);

-- Access points / gates
CREATE TABLE public.access_points (
    id integer NOT NULL,
    name text NOT NULL,
    conjunto_id text NOT NULL
);

-- Visitor logs
CREATE TABLE public.visitor_logs (
    id integer NOT NULL,
    apartment text NOT NULL,
    visitor_name text NOT NULL,
    date date NOT NULL,
    status text NOT NULL,
    entry_time text,
    exit_time text,
    access_point_id integer,
    conjunto_id text NOT NULL
);

-- Package / courier logs
CREATE TABLE public.package_logs (
    id integer NOT NULL,
    apartment text NOT NULL,
    courier text NOT NULL,
    tracking_number text,
    received_date timestamp with time zone DEFAULT now(),
    status text NOT NULL,
    conjunto_id text NOT NULL
);

-- Chatbot interaction tracking
CREATE TABLE public.chatbot_interactions (
    id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    conjunto_id text NOT NULL
);

-- ============================================
-- SEQUENCES
-- ============================================

CREATE SEQUENCE public.providers_id_seq AS integer START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE public.users_id_seq AS integer START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE public.bookings_id_seq AS integer START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE public.due_dates_id_seq AS integer START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE public.tasks_id_seq AS integer START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE public.expenses_id_seq AS integer START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE public.incomes_id_seq AS integer START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE public.access_points_id_seq AS integer START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE public.visitor_logs_id_seq AS integer START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE public.package_logs_id_seq AS integer START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE public.chatbot_interactions_id_seq AS bigint START WITH 1 INCREMENT BY 1;

-- ============================================
-- PRIMARY KEYS
-- ============================================

ALTER TABLE ONLY public.conjuntos ADD CONSTRAINT conjuntos_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.user_profiles ADD CONSTRAINT user_profiles_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.residents ADD CONSTRAINT residents_pkey PRIMARY KEY (apartment, conjunto_id);
ALTER TABLE ONLY public.account_status ADD CONSTRAINT account_status_pkey PRIMARY KEY (apartment, conjunto_id);
ALTER TABLE ONLY public.providers ADD CONSTRAINT providers_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.internal_staff ADD CONSTRAINT internal_staff_pkey PRIMARY KEY (name, conjunto_id);
ALTER TABLE ONLY public.users ADD CONSTRAINT users_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.user_roles ADD CONSTRAINT user_roles_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.common_areas ADD CONSTRAINT common_areas_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.bookings ADD CONSTRAINT bookings_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.reservations ADD CONSTRAINT reservations_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.due_dates ADD CONSTRAINT due_dates_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.tasks ADD CONSTRAINT tasks_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.expenses ADD CONSTRAINT expenses_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.incomes ADD CONSTRAINT incomes_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.access_points ADD CONSTRAINT access_points_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.visitor_logs ADD CONSTRAINT visitor_logs_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.package_logs ADD CONSTRAINT package_logs_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.chatbot_interactions ADD CONSTRAINT chatbot_interactions_pkey PRIMARY KEY (id);

-- ============================================
-- UNIQUE CONSTRAINTS
-- ============================================

ALTER TABLE ONLY public.users ADD CONSTRAINT users_email_key UNIQUE (email);

-- ============================================
-- FOREIGN KEYS
-- ============================================

ALTER TABLE ONLY public.user_profiles ADD CONSTRAINT user_profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id);
ALTER TABLE ONLY public.user_profiles ADD CONSTRAINT user_profiles_conjunto_id_fkey FOREIGN KEY (conjunto_id) REFERENCES public.conjuntos(id);
ALTER TABLE ONLY public.residents ADD CONSTRAINT residents_conjunto_id_fkey FOREIGN KEY (conjunto_id) REFERENCES public.conjuntos(id);
ALTER TABLE ONLY public.account_status ADD CONSTRAINT account_status_conjunto_id_fkey FOREIGN KEY (conjunto_id) REFERENCES public.conjuntos(id);
ALTER TABLE ONLY public.providers ADD CONSTRAINT providers_conjunto_id_fkey FOREIGN KEY (conjunto_id) REFERENCES public.conjuntos(id);
ALTER TABLE ONLY public.internal_staff ADD CONSTRAINT internal_staff_conjunto_id_fkey FOREIGN KEY (conjunto_id) REFERENCES public.conjuntos(id);
ALTER TABLE ONLY public.users ADD CONSTRAINT users_conjunto_id_fkey FOREIGN KEY (conjunto_id) REFERENCES public.conjuntos(id);
ALTER TABLE ONLY public.user_roles ADD CONSTRAINT user_roles_conjunto_id_fkey FOREIGN KEY (conjunto_id) REFERENCES public.conjuntos(id);
ALTER TABLE ONLY public.common_areas ADD CONSTRAINT common_areas_conjunto_id_fkey FOREIGN KEY (conjunto_id) REFERENCES public.conjuntos(id);
ALTER TABLE ONLY public.bookings ADD CONSTRAINT bookings_conjunto_id_fkey FOREIGN KEY (conjunto_id) REFERENCES public.conjuntos(id);
ALTER TABLE ONLY public.reservations ADD CONSTRAINT reservations_common_area_id_fkey FOREIGN KEY (common_area_id) REFERENCES public.common_areas(id);
ALTER TABLE ONLY public.due_dates ADD CONSTRAINT due_dates_conjunto_id_fkey FOREIGN KEY (conjunto_id) REFERENCES public.conjuntos(id);
ALTER TABLE ONLY public.tasks ADD CONSTRAINT tasks_conjunto_id_fkey FOREIGN KEY (conjunto_id) REFERENCES public.conjuntos(id);
ALTER TABLE ONLY public.expenses ADD CONSTRAINT expenses_conjunto_id_fkey FOREIGN KEY (conjunto_id) REFERENCES public.conjuntos(id);
ALTER TABLE ONLY public.expenses ADD CONSTRAINT expenses_provider_id_fkey FOREIGN KEY (provider_id) REFERENCES public.providers(id);
ALTER TABLE ONLY public.incomes ADD CONSTRAINT incomes_conjunto_id_fkey FOREIGN KEY (conjunto_id) REFERENCES public.conjuntos(id);
ALTER TABLE ONLY public.access_points ADD CONSTRAINT access_points_conjunto_id_fkey FOREIGN KEY (conjunto_id) REFERENCES public.conjuntos(id);
ALTER TABLE ONLY public.visitor_logs ADD CONSTRAINT visitor_logs_conjunto_id_fkey FOREIGN KEY (conjunto_id) REFERENCES public.conjuntos(id);
ALTER TABLE ONLY public.visitor_logs ADD CONSTRAINT visitor_logs_access_point_id_fkey FOREIGN KEY (access_point_id) REFERENCES public.access_points(id);
ALTER TABLE ONLY public.package_logs ADD CONSTRAINT package_logs_conjunto_id_fkey FOREIGN KEY (conjunto_id) REFERENCES public.conjuntos(id);
ALTER TABLE ONLY public.chatbot_interactions ADD CONSTRAINT chatbot_interactions_conjunto_id_fkey FOREIGN KEY (conjunto_id) REFERENCES public.conjuntos(id);

-- ============================================
-- SEQUENCE OWNERSHIP
-- ============================================

ALTER SEQUENCE public.providers_id_seq OWNED BY public.providers.id;
ALTER SEQUENCE public.users_id_seq OWNED BY public.users.id;
ALTER SEQUENCE public.bookings_id_seq OWNED BY public.bookings.id;
ALTER SEQUENCE public.due_dates_id_seq OWNED BY public.due_dates.id;
ALTER SEQUENCE public.tasks_id_seq OWNED BY public.tasks.id;
ALTER SEQUENCE public.expenses_id_seq OWNED BY public.expenses.id;
ALTER SEQUENCE public.incomes_id_seq OWNED BY public.incomes.id;
ALTER SEQUENCE public.access_points_id_seq OWNED BY public.access_points.id;
ALTER SEQUENCE public.visitor_logs_id_seq OWNED BY public.visitor_logs.id;
ALTER SEQUENCE public.package_logs_id_seq OWNED BY public.package_logs.id;
ALTER SEQUENCE public.chatbot_interactions_id_seq OWNED BY public.chatbot_interactions.id;

-- ============================================
-- DEFAULT VALUES FOR SEQUENCE COLUMNS
-- ============================================

ALTER TABLE ONLY public.providers ALTER COLUMN id SET DEFAULT nextval('public.providers_id_seq'::regclass);
ALTER TABLE ONLY public.users ALTER COLUMN id SET DEFAULT nextval('public.users_id_seq'::regclass);
ALTER TABLE ONLY public.bookings ALTER COLUMN id SET DEFAULT nextval('public.bookings_id_seq'::regclass);
ALTER TABLE ONLY public.due_dates ALTER COLUMN id SET DEFAULT nextval('public.due_dates_id_seq'::regclass);
ALTER TABLE ONLY public.tasks ALTER COLUMN id SET DEFAULT nextval('public.tasks_id_seq'::regclass);
ALTER TABLE ONLY public.expenses ALTER COLUMN id SET DEFAULT nextval('public.expenses_id_seq'::regclass);
ALTER TABLE ONLY public.incomes ALTER COLUMN id SET DEFAULT nextval('public.incomes_id_seq'::regclass);
ALTER TABLE ONLY public.access_points ALTER COLUMN id SET DEFAULT nextval('public.access_points_id_seq'::regclass);
ALTER TABLE ONLY public.visitor_logs ALTER COLUMN id SET DEFAULT nextval('public.visitor_logs_id_seq'::regclass);
ALTER TABLE ONLY public.package_logs ALTER COLUMN id SET DEFAULT nextval('public.package_logs_id_seq'::regclass);
ALTER TABLE ONLY public.chatbot_interactions ALTER COLUMN id SET DEFAULT nextval('public.chatbot_interactions_id_seq'::regclass);

-- ============================================
-- FUNCTIONS
-- ============================================

CREATE OR REPLACE FUNCTION public.get_my_conjunto_id()
RETURNS text
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  RETURN (SELECT conjunto_id FROM public.user_profiles WHERE id = auth.uid());
END;
$$;

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
begin
  insert into public.user_profiles (id, full_name, avatar_url, email, role, trial_expires_at)
  values (
    new.id,
    coalesce(new.raw_user_meta_data ->> 'full_name', new.raw_user_meta_data ->> 'name', new.email),
    new.raw_user_meta_data ->> 'avatar_url',
    new.email,
    'trial',
    now() + interval '30 days'
  );
  return new;
end;
$$;

-- ============================================
-- TRIGGERS
-- ============================================

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW
  EXECUTE FUNCTION public.handle_new_user();

-- ============================================
-- ROW LEVEL SECURITY
-- ============================================

-- Enable RLS on all tables
ALTER TABLE public.conjuntos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.residents ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.account_status ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.providers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.internal_staff ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_roles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.common_areas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bookings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reservations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.due_dates ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.expenses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.incomes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.access_points ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.visitor_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.package_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.chatbot_interactions ENABLE ROW LEVEL SECURITY;

-- Tenant-isolation policies (get_my_conjunto_id)
CREATE POLICY "Enable access for own conjunto" ON public.access_points FOR ALL USING (conjunto_id = get_my_conjunto_id());
CREATE POLICY "Enable access for own conjunto" ON public.account_status FOR ALL USING (conjunto_id = get_my_conjunto_id());
CREATE POLICY "Enable access for own conjunto" ON public.bookings FOR ALL USING (conjunto_id = get_my_conjunto_id());
CREATE POLICY "Enable access for own conjunto" ON public.chatbot_interactions FOR ALL USING (conjunto_id = get_my_conjunto_id());
CREATE POLICY "Enable access for own conjunto" ON public.common_areas FOR ALL USING (conjunto_id = get_my_conjunto_id());
CREATE POLICY "Enable access for own conjunto" ON public.due_dates FOR ALL USING (conjunto_id = get_my_conjunto_id());
CREATE POLICY "Enable access for own conjunto" ON public.expenses FOR ALL USING (conjunto_id = get_my_conjunto_id());
CREATE POLICY "Enable access for own conjunto" ON public.incomes FOR ALL USING (conjunto_id = get_my_conjunto_id());
CREATE POLICY "Enable access for own conjunto" ON public.internal_staff FOR ALL USING (conjunto_id = get_my_conjunto_id());
CREATE POLICY "Enable access for own conjunto" ON public.package_logs FOR ALL USING (conjunto_id = get_my_conjunto_id());
CREATE POLICY "Enable access for own conjunto" ON public.providers FOR ALL USING (conjunto_id = get_my_conjunto_id());
CREATE POLICY "Enable access for own conjunto" ON public.residents FOR ALL USING (conjunto_id = get_my_conjunto_id());
CREATE POLICY "Enable access for own conjunto" ON public.tasks FOR ALL USING (conjunto_id = get_my_conjunto_id());
CREATE POLICY "Enable access for own conjunto" ON public.user_roles FOR ALL USING (conjunto_id = get_my_conjunto_id());
CREATE POLICY "Enable access for own conjunto" ON public.users FOR ALL USING (conjunto_id = get_my_conjunto_id());
CREATE POLICY "Enable access for own conjunto" ON public.visitor_logs FOR ALL USING (conjunto_id = get_my_conjunto_id());

-- Conjuntos policies
CREATE POLICY "Allow authenticated users to insert conjuntos" ON public.conjuntos FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Enable SELECT for own conjunto" ON public.conjuntos FOR SELECT USING (id = get_my_conjunto_id());
CREATE POLICY "Enable UPDATE for own conjunto" ON public.conjuntos FOR UPDATE USING (id = get_my_conjunto_id());
CREATE POLICY "Enable DELETE for own conjunto" ON public.conjuntos FOR DELETE USING (id = get_my_conjunto_id());

-- User profiles policies
CREATE POLICY "Allow individual read access" ON public.user_profiles FOR SELECT USING (auth.uid() = id);
CREATE POLICY "Allow individual update access" ON public.user_profiles FOR UPDATE USING (auth.uid() = id);
CREATE POLICY "Los usuarios pueden ver y editar su propio perfil." ON public.user_profiles FOR ALL USING (auth.uid() = id) WITH CHECK (auth.uid() = id);

-- Reservations policy
CREATE POLICY "Allow admin to manage their own reservations" ON public.reservations FOR ALL USING (
    (SELECT conjunto_id FROM public.user_profiles WHERE id = auth.uid()) = conjunto_id::text
);

-- ============================================
-- INDEXES
-- ============================================

-- Residents lookup by apartment
CREATE INDEX idx_residents_apartment ON public.residents (apartment);
-- Account status lookup by apartment
CREATE INDEX idx_account_status_apartment ON public.account_status (apartment);
-- Foreign key performance
CREATE INDEX idx_expenses_provider_id ON public.expenses (provider_id);
CREATE INDEX idx_visitor_logs_access_point_id ON public.visitor_logs (access_point_id);
CREATE INDEX idx_reservations_common_area_id ON public.reservations (common_area_id);
-- Tenant isolation
CREATE INDEX idx_residents_conjunto_id ON public.residents (conjunto_id);
CREATE INDEX idx_account_status_conjunto_id ON public.account_status (conjunto_id);
CREATE INDEX idx_providers_conjunto_id ON public.providers (conjunto_id);
CREATE INDEX idx_expenses_conjunto_id ON public.expenses (conjunto_id);
CREATE INDEX idx_incomes_conjunto_id ON public.incomes (conjunto_id);
