import { test as base, type PlaywrightTestArgs, type PlaywrightWorkerArgs } from '@playwright/test';
import { chromium, type Browser, type BrowserContext, type Page } from '@playwright/test';

// Custom test fixtures
type TestFixtures = {
  authenticatedPage: Page;
  superAdminAuth: string;
};

type WorkerFixtures = {
  browser: Browser;
  superAdminStorageState: string;
};

export const test = base.extend<TestFixtures, WorkerFixtures>({
  // Browser fixture for workers
  browser: async ({}, use) => {
    const browser = await chromium.launch({ headless: true });
    await use(browser);
    await browser.close();
  },

  // Super admin storage state for authenticated tests
  superAdminStorageState: async ({ browser }, use) => {
    // In CI, this would be generated by a setup script
    // For local dev, use existing auth state
    const storageState = 'tests/.auth/superadmin.json';
    await use(storageState);
  },

  // Authenticated page for each test
  authenticatedPage: async ({ browser, superAdminStorageState }, use) => {
    const context = await browser.newContext({
      storageState: superAdminStorageState,
      viewport: { width: 1280, height: 720 },
    });
    const page = await context.newPage();
    await use(page);
    await context.close();
  },
});

export { expect } from '@playwright/test';